- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker Image
      docker_image:
        name: prakruthi810/banking-project-demo
        tag: "4.0"
        source: pull

    - name: Deploy Docker Container
      docker_container:
        name: banking_project_demo
        image: prakruthi810/banking-project-demo:4.0
        state: started
        restart_policy: unless-stopped
        published_ports:
          - "8084:8081"
